### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by xfg** [bravi-software/knextancy#4]
``` javascript
knextancy.tenant(knex, 'tbl').then(function (tenantKnex) {
  tenantKnex('$_users').where({
    first_name: 'Test',
    last_name:  'User'
  }).select('id')
});
```

```
ReferenceError: regeneratorRuntime is not defined
    at Object.callee$0$0 [as tenant] (/path/node_modules/knextancy/lib/tenant.js:96:10)
```

I have installed knex 0.10.0

**Comment by maxclaus** [comment]
That is weird. What version of knextancy are you using?

**Comment by maxclaus** [comment]
Please check out the service example - https://github.com/bravi-software/knextancy-example.

**Comment by xfg** [comment]
I am using knextancy 2.1.0. I can't check the service example because I use MySQL, not PostgreSQL.

**Comment by maxclaus** [comment]
Probably is missing some configuration for babel in the build.
I usually use it with babel so I guess is that because I have never seen it before. 
I will update the babel configuration later today. Probably tomorrow you have a new version with this fixed.

**Comment by maxclaus** [comment]
@xfg sorry to take so long to fix that. Using version `2.1.1` now you should be able to use the lib without depending on Babel. Could you test that for me?
