### ISSUE TITLE
Initial configuration with Bookshelf

### ISSUE THREAD

**Issue by robertoclavijob** [bravi-software/knextancy#5]
Hi

I am using Bookshelf.js in my app, similar to quickstart example http://bookshelfjs.org/

How can I configure this to use knextancy

var knex = require('knex')({
  client: 'mysql',
  connection: {
    host     : '127.0.0.1',
    user     : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test',
    charset  : 'utf8'
  }
});

var bookshelf = require('bookshelf')(knex);

var User = bookshelf.Model.extend({
  tableName: 'users'
});

Regards
Roberto

**Comment by maxclaus** [comment]
I have never tried out the knextancy with bookshelf. Although I think it should work anyway.
Basically you could test it following the first example in the [docs](https://github.com/bravi-software/knextancy#knextancy---knex-with-multitenancy).
Here is an adapted version of that example, but using bookshelf (I have not tested it):

``` js
var knextancy = require('knextancy');
var createBookshelf = require('bookshelf');

var knex = require('knex')({
  client: 'mysql',
  connection: {
  host : '127.0.0.1',
  user : 'your_database_user',
  password : 'your_database_password',
  database : 'myapp_test',
  charset : 'utf8'
  }
});

var tenantId = 1;
knextancy.tenant(knex, tenantId).then(function (tenantKnex) {
  // the tenantKnex object contains the tenantId as an attribute
  console.log(tenantKnex.tenantId);

  var bookshelf = createBookshelf(tenantKnex);

  var User = bookshelf.Model.extend({
    tableName: 'users'
  });
});
```

**Comment by robertoclavijob** [comment]
I'll test it thanks
