### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by robertoclavijob** [bravi-software/knextancy#6]
Hi: 
I am trying to get a simple query running using knextancy, but without success.

I working with this example
https://github.com/dYale/knexBlogBackend/

I added a route in the index file

```
app.get('/', function (req, res) {
    db.select().from('users').then(function (result) {
        res.json(result);
    })
});
```

Testing with postman it works ok.

Then I tried to use knextancy in this way 

```

var express = require('express');  
var app = express();  
var db  = require('./db');
var knextancy = require('knextancy');

var port = 4000;

app.listen(port);  
console.log("Listening on port", port);

app.get('/', function (req, res) {
    var tenantId = 1;
    knextancy.tenant(db, tenantId).then(function (tenantKnex) {

        // the tenantKnex object contains the tenantId as an attribute 
        console.log(tenantKnex.tenantId);

        tenantKnex('$_users').select().then(function (result) {
            res.json(result);
        })
    }).catch(function (error){
        console.log(error);
    });
});

```

But I am getting this error in the catch 
`Cannot read property 'tableName' of undefined`

What do I need additionally to get it running?

Thanks in advance
Roberto

**Comment by maxclaus** [comment]
Hi @robertoclavijob,

It was missing pass the [migrations configuration](https://github.com/bravi-software/knextancy-example/blob/master/config/knex.js#L15). I have fixed the knextancy to not crash in case it is missing. The version https://github.com/bravi-software/knextancy/releases/tag/v2.1.2 should work without that custom configuration.

**Comment by robertoclavijob** [comment]
Thanks @maxcnunes 

With 2.1.2 the tables were successfully created.  But when I try to query the tables, consuming get service from postman, I am getting this error

`Listening on port 4000
Error: Error: ENOENT: no such file or directory, scandir '/home/roberto/sites/knexBlogBackend/seeds'
`
**Migrations**
`
exports.up = function(knex, Promise) {

```
return Promise.all([

    knex.schema.createTable('$_users', function(table) {
        table.increments('uid').primary();
        table.string('username');
        table.string('password');
        table.string('name');
        table.string('email');
        table.timestamps();
    }),

])
```

};

exports.down = function(knex, Promise) {

```
return Promise.all([
    knex.schema.dropTable('$_users'),
])
```

};`

**The route**

`var express = require('express');  
var app = express();  
var db  = require('./db');
var knextancy = require('knextancy');

var port = 4000;

app.listen(port);  
console.log("Listening on port", port);

app.get('/', function (req, res) {
    var tenantId = req.headers['x-client-id'];
    knextancy.tenant(db, tenantId).then(function (tenantKnex) {
        // the tenantKnex object contains the tenantId as an attribute
        console.log(tenantKnex.tenantId);

```
    tenantKnex('$_users').select().then(function (result) {
        res.json(result);
    })
}).catch(function (error){
    console.log("Error: " + error);
});
```

});`

The tables
https://drive.google.com/file/d/0B4K4Kq6WqsupRk1TRmd4Nm9tYlU/view?usp=sharing

**Comment by maxclaus** [comment]
The knextancy expect you have seed tasks. Create a empty folder at least to avoid that problem. Example: https://github.com/bravi-software/knextancy-example/tree/master/db/seeds.

**Comment by robertoclavijob** [comment]
Thanks Max, it works
